export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORMS_HOME: '/home',
  CREATE_FORM: '/forms/new',
  BUILDER: '/builder/:formId',
  FORM_SETTINGS: '/forms/:formId/settings',
  RESPONDENT: '/f/:formId',
  RESPONSES_DASHBOARD: '/responses/:formId',
  LOTTERY: '/lottery/:formId',
  getBuilderRoute: (formId: string) => `/builder/${formId}`,
  getFormSettingsRoute: (formId: string) => `/forms/${formId}/settings`,
  getRespondentRoute: (formId: string) => `/f/${formId}`,
  getResponsesDashboardRoute: (formId: string) => `/responses/${formId}`,
  getLotteryRoute: (formId: string) => `/lottery/${formId}`,
} as const;
