// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhyveqffsitdgwyflvgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloeXZlcWZmc2l0ZGd3eWZsdmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyOTgzMTcsImV4cCI6MjA3ODg3NDMxN30.CuGbFvmw7Ta71EcdFw-mT8dENoPXo71he-5kQEZtZMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});